"""user.is_participant

Revision ID: 863bcd16f052
Revises: 49a5450ae9c2
Create Date: 2024-06-09 01:35:20.788066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863bcd16f052'
down_revision: Union[str, None] = '49a5450ae9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_participant', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_participant')
    # ### end Alembic commands ###
